### ISSUE TITLE
Setup DNS to use rehab-app.ru

### ISSUE THREAD

**Issue by flancer64** [flancer32/pwa-ra-mob#110]
Чтобы можно было использовать домен для входа в приложение, нужно в домене указать, что корневой домен (символ @ обычно используется) ведёт на ip-адрес 2.59.41.160, а также создать хост desk.rehab-app.ru, который также нужно направить на адрес 2.59.41.160.

**Comment by flancer64** [comment]
@minkinr , вы уже зарегистрировали домен (rehab-app.ru или какой-либо другой)?

**Comment by minkinr** [comment]
Да

**Comment by flancer64** [comment]
@minkinr , отлично! Теперь нужно настроить DNS, чтобы этот домен вёл на сервер с ip-адресом 2.59.41.160.
