### ISSUE TITLE
Категории программ: Template меняем на  Popular (программно также как Typical).

### ISSUE THREAD

**Issue by minkinr** [flancer32/pwa-ra-mob#113]

**Comment by flancer64** [comment]
Выложил изменения на пилота:
![image](https://user-images.githubusercontent.com/5052385/192318660-91fad23d-6bc6-42a4-b25c-8c6beb0caf09.png)

**Comment by minkinr** [comment]
I. Популярные -  типовых программ много и в них сложно разобраться. Некоторые из типовых пользуются спросом, но не понятно как их быстро найти. Решения два 1) либо отдельня категория - популярные, 2) либо в типовых сверху показывать 3-5 популярных программ. II. Думаю еще понадобится, категория избранные. Например, человек выбрал себе программу 15:35, 23 сентября 2022 г., Alex Gusev ***@***.***>:
@minkinr , у нас есть три типа программ:

типовая программа: создана администратором приложения, может быть использована врачами и пациентами для создания своих программ.
назначенная программа: создана врачом для конкретного пациента, редактируется только врачом.
персональная программа: создана пациентом для самого себя.

popular - это новый тип или программа может быть одновременно, например, typical & popular?

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>
-- Отправлено из мобильного приложения Яндекс Почты
