### ISSUE TITLE
Player:  add i- info button for exercise information.

### ISSUE THREAD

**Issue by minkinr** [flancer32/pwa-ra-mob#114]
Top Right corner

**Comment by flancer64** [comment]
Если мы хотим давать эту информацию для упражнения (описание и комментарии врача), то нужно добавлять диалоговое окно с деталями упражнения. По "тапу" на упражнении этот диалог должен открываться и показывать детали конкретного упражнения. Иначе мы "заспамим" список упражнений текстовой информацией. ОК, добавляю диалог.

**Comment by flancer64** [comment]
Вот так будут выглядеть детали упражнения в программе в свёрнутом виде:
![image](https://user-images.githubusercontent.com/5052385/192279830-79b8af98-6fdc-43be-95b2-0c66e3067381.png)

а так - в развёрнутом:
![image](https://user-images.githubusercontent.com/5052385/192279949-076d1fc0-dcc8-43ef-8130-478d47a7c9db.png)

**Comment by flancer64** [comment]
Выложился на пилота.

**Comment by minkinr** [comment]
Сейчас непонятно, что для упражнений есть описание. Надо сделать либо три точки в праом верхнем углу карточки упражнения. Или название упражнения сделать синим.

**Comment by flancer64** [comment]
Сделал так:
![image](https://user-images.githubusercontent.com/5052385/193055621-63bc52d5-5bde-4289-9efe-55cded42a69e.png)
