### ISSUE TITLE
Экран регистрации пациента

### ISSUE THREAD

**Issue by minkinr** [flancer32/pwa-ra-mob#117]
1) собирать телефон пользователя
2) добавить телефон пользователя в картотеку 
3) добавить возможность закрыть\отменить экран регистрации (например если он открыт по ошибке)
4) добавить восстановление пароля

 Optional:
5) Добавить автозапоминание логина/emaila.

**Comment by flancer64** [comment]
> 4. добавить восстановление пароля

Это отдельная, довольно обширная задача. У нас она была в backlog'е - 
https://github.com/flancer32/pwa-ra-mob/issues/128

Повысил в приоритете и перенёс в ToDo.

**Comment by flancer64** [comment]
Выложил изменения на пилота.
