### ISSUE TITLE
Add phone and clinic to doc invitation (in desk app)

### ISSUE THREAD

**Issue by minkinr** [flancer32/pwa-ra-mob#121]
Desk: приглашение доктору, добавить сбор номер телефона (must) и название клиники (optional) зафиксировать их в базе.

**Comment by flancer64** [comment]
Телефон - это атрибут пользователя (`app_user`). Он будет нужен и для пациентов тоже (#117). А вот название клиники - это атрибут именно доктора. Для обеспечения консистентности данных нужно делать кодификатор клиник (это если по-взрослому) - т.е. блок функционала, в чём-то аналогичный тэгам.

**Comment by flancer64** [comment]
Добавил реестр клиник:

![Image](https://user-images.githubusercontent.com/5052385/192747061-065e3d6a-eb74-438a-8c2e-6635754781a5.png)

Можно добавлять и редактировать клиники (имя). Удалять нельзя (только напрямую из БД).

**Comment by flancer64** [comment]
Приглашение для доктора сейчас выглядит вот так:
![image](https://user-images.githubusercontent.com/5052385/192761728-1a1c8de1-cd4b-4ce6-bd0d-768c08503a36.png)

**Comment by flancer64** [comment]
задачу закончил, но на пилота пока не выкладывал - она связана с https://github.com/flancer32/pwa-ra-mob/issues/117
