### ISSUE TITLE
Экран Программы: поиск

### ISSUE THREAD

**Issue by minkinr** [flancer32/pwa-ra-mob#125]
1) Добавить поиск но названию программ

DONE: 
1) Сделать заголовок на экране Программы, также как в Конструкторе
2) Фильтры "ноги...шея" желательно разместить во второй строчке.-》 реализовано по-другому (ОК)

**Comment by flancer64** [comment]
@minkinr , у нас сть два места, где может применяться поиск программы по названию:
1. В Конструкторе, при выборе программы-донора:
![image](https://user-images.githubusercontent.com/5052385/195074123-7e7ef414-2e45-4515-9ff7-5241eb1e8607.png)

2. В списке программ:
![image](https://user-images.githubusercontent.com/5052385/195074263-7db47fe7-293b-4d92-9309-a0f6662fa548.png)

Где именно добавлять поиск?

**Comment by minkinr** [comment]
И там и там

**Comment by flancer64** [comment]
@minkinr , какой должен быть алгоритм поиска по программам - AND или OR? У нас сейчас есть три параметра для поиска:
1. ключ поиска: строка в свободной форме;
2. тип программы: мои, назначенные, типовые, популярные;
3. зона тела: руки, ноги, ...;

![image](https://user-images.githubusercontent.com/5052385/195267246-de53630e-486d-4496-bcb2-45f95cea1a00.png)

С моей точки зрения, наибольшим приоритетом обладает тип (он может быть только один - там radiobutton), после этого можно применять фильтрацию по зонам тела (сами зоны - по OR, вместе с типом - по AND), и уже после этого - фильтрация по ключу поиска (название или описание программы). Т.е., сужающийся поиск (по AND) даёт возможность на каждом шаг уменьшать кол-во программ в поисковой выборке.

**Comment by minkinr** [comment]
Все так. Сужающийся поиск между группами AND. Внутри группы OR. 

Единственное я бы сделала  по типу программ тоже checkbox: тогда можно искать по всем программам или типовая+популярная.

**Comment by flancer64** [comment]
> я бы сделала по типу программ тоже checkbox: тогда можно искать по всем программам или типовая+популярная.

Сделал.

![image](https://user-images.githubusercontent.com/5052385/195404627-a454ea00-60c4-44cf-b50d-c57af6a545e0.png)

и совместил с поиском по ключу:
![image](https://user-images.githubusercontent.com/5052385/195404802-6b395007-8079-4adc-819e-7fef53980537.png)

**Comment by flancer64** [comment]
Также совместил код фильтрации/поиска по упражнениям с кодом фильтрации/поиска по программам. Чтобы у них была одна структура. Уж очень там запутано, пришлось даже [диаграмму сделать](https://github.com/flancer32/pwa-ra-base/blob/b5975493b12f17b7c8d281f3aeb41b1823c07013/docs/dev/front/constructor/components.md), чтобы упорядочиться.
