### ISSUE TITLE
Блокировка плейера после тестового периода

### ISSUE THREAD

**Issue by minkinr** [flancer32/pwa-ra-mob#131]
1) блокировка плейера после тестового периода и просмотр назначеннрй программы без анимации
2) уменьшить тестовый срок до 3ех дней

**Comment by flancer64** [comment]
Поставил блокировку экрана проигрывателя. Пока что так:
![image](https://user-images.githubusercontent.com/5052385/195034714-27ad5adb-250c-4ebe-95c3-609ac4f728f4.png)

Нужно будет ставить переход на оформление подписки, но у нас есть только базовый функционал в настройках:
![image](https://user-images.githubusercontent.com/5052385/195035005-f58ff964-ec9a-4bb3-9f65-eb08ca883633.png)

**Comment by flancer64** [comment]
Проверил создание подписки для нового клиента - работает. Только изменил срок демо-подписки с 7 дней до 3-х.

**Comment by flancer64** [comment]
Добавил в админку возможность отменить действующую подписку:
![image](https://user-images.githubusercontent.com/5052385/195061268-c1f4502d-c3a9-46cd-b685-c8adb0d8a0d4.png)
