### ISSUE TITLE
Подписка: сумма счета

### ISSUE THREAD

**Issue by minkinr** [flancer32/pwa-ra-mob#152]
@flancer64 

Сумма счета должна вводится админом вручную в desk'е и показываться пользователю перед оплатой счета.

**Comment by flancer64** [comment]
Сейчас так и есть:

![Image](https://user-images.githubusercontent.com/5052385/199154654-88d7862c-b592-4cb5-ac7d-b1d57946e424.png)

Тоже похоже на старый код в мобильном приложении.
