### ISSUE TITLE
Подписка: сообщение об оплате

### ISSUE THREAD

**Issue by minkinr** [flancer32/pwa-ra-mob#153]
@flancer64 

сообщение об оплате только после нажатия на кнопку оплатить, а не до.

Сообщение об оплате "Оплата на проверке. Подписка активирована до dd-mmm-yyyy".  

![Screenshot_20221031-083901_Chrome.jpg](https://user-images.githubusercontent.com/103753072/198955654-17ef3e5c-a50a-4256-94c2-ce854ef6b34c.jpg)

**Comment by flancer64** [comment]
Было сделано ещё в https://github.com/flancer32/pwa-ra-mob/issues/147 Скорее всего, проверялся старый код.
