### ISSUE TITLE
New session conflicts on user registration

### ISSUE THREAD

**Issue by minkinr** [flancer32/pwa-ra-mob#170]

**Comment by minkinr** [comment]
На приложеном экране, после нажатия на зарегистироваться - не регистрирует. переходит на экран входа.
![Снимок экрана 2022-11-09 094643](https://user-images.githubusercontent.com/103753072/200758807-74e8239d-918b-41a4-b858-a41a2c427e2f.png)

**Comment by flancer64** [comment]
Вот такая ошибка в логе, которая соответствует данному событию:
```
11/09 06:40:19.389 (error): error: insert into "app_user_session" ("date_created", "front_ref", "user_ref", "uuid") values ($1, $2, $3, $4) returning "uuid" - duplicate key value violates unique constraint "app_user_session_front"
```

Думаю, что она вызвана тем, что регистрация нового пользователя производилась без завершения сессии для пользователя существующего. Т.е., если залогиниться под каким-либо пользователем, а потом перейти в экран регистрации и зарегистрироваться, то возникает конфликт между существующей сессией и вновь устанавливаемой. Ограничение app_user_session_front как раз об этом - чтобы с одного браузера не было две разные сессии для двух разных пользователей.

@minkinr , для обычного пользователя такая ситуация является, скорее, исключительной. Но т.к. мы тестируем от лица разных ролей, то нам проще с таким столкнуться. Я обычно полностью удаляю приложение (через Settings), если хочу сменить роль.

В принципе, возможно два пути решения:
* закрывать принудительно имеющуюся сессию с этого же фронта, если пришёл запрос на новую сессию;
* отказывать в посещении анонимных экранов, если у пользователя есть аутентификация;

@minkinr , по какому пути идём?
