### ISSUE TITLE
Send email with invite from Share screen

### ISSUE THREAD

**Issue by minkinr** [flancer32/pwa-ra-mob#171]
@flancer64 

На Huawei qr code не распознается. Отпраить кнопкой поделиться очень неудобно, так как 
1) месенджеры сначала просят ввести контакты 
2) контактов  нет перед глазами 
3) самый удобный отправка по емейл, но опять же нет емейла перед глазами. 

Может добавить в текст приглашения емейл пациента?
![photo_2022-11-09_10-35-11](https://user-images.githubusercontent.com/103753072/200767294-8cb27d0f-1cb2-4de5-98a4-c27767edab22.jpg)

**Comment by flancer64** [comment]
Нужно добавить возможность отправки email'ов с приглашением через само приложение. По возможности, продублировать контакты (email, phone) в экране "Поделиться".

**Comment by flancer64** [comment]
Для распознавания QR-кодов нужны специальные программы в смартфоне. В некоторых моделях распознавание кодов встроено в камеру, в других - нужно закачивать сторонние.

Функция "[Поделиться](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/share)" доступна не во всех браузерах и набор информации, которая может быть передана через функцию, достаточно скуден:
* url
* text
* title
* files (не используем)

```
const data = {
    title: this.$t('lib.prg.share.msg.title'),
    text: this.$t('lib.prg.share.msg.text'),
    url,
};
```

После ввода данных и генерации приглашения вот такое состояние для десктопа (на смартфоне две кнопки - "Поделиться" и "Отправить"):
![image](https://user-images.githubusercontent.com/5052385/200908493-8a3910b1-28d7-481c-b009-68dc222d9783.png)

После отправки email'а с приглашением появляется подтверждение:
![image](https://user-images.githubusercontent.com/5052385/200907761-eef2547e-ee2f-42fb-b5df-777282182bb9.png)

**Comment by flancer64** [comment]
Вот так выглядит диалог для мобильного:
![image](https://user-images.githubusercontent.com/5052385/200910613-47311424-6e1b-4f4a-9c50-52a1192e5440.png)

По кнопке "Поделиться" программа передаёт управление операционной системе устройства, на котором выполняется.

**Comment by flancer64** [comment]
Выложился на live.
