### ISSUE TITLE
Add patient to program (doctors only)

### ISSUE THREAD

**Issue by minkinr** [flancer32/pwa-ra-mob#172]
1) В начале мы планировали вносить контакты пациента на этапе формирования программы. Предлагаю к этому вернуться.

2) пациент должен появляться у врача на кнопке пациенты сразу как он его внес/зарегистрировал

![Screenshot_20221109-104553_Gallery.jpg](https://user-images.githubusercontent.com/103753072/200770320-ec8920c7-487e-48da-9e6a-b8ab23401f4c.jpg)

![Screenshot_20221109-104615_Gallery.jpg](https://user-images.githubusercontent.com/103753072/200770348-3e4fd4f8-4647-4691-8830-4221e72bb4c5.jpg)

**Comment by flancer64** [comment]
Добавил объект в IDB, фронт-модель для пациента, event для синхронизации данных по пациентам с бэка на фронт.

**Comment by flancer64** [comment]
Добавил диалог для выбора пациента к форме редактирования программы:
![image](https://user-images.githubusercontent.com/5052385/202763693-b251920e-bb05-4193-8202-d478fd185ec3.png)

Пока что всё это работает на фронте и на бэк не передаётся. Плюс нужно будет добавлять на форму выбора опцию по добавлению новой карточки клиента.

**Comment by flancer64** [comment]
Вчера добавил диалог для регистрации карточки нового пациента в Конструкторе:
![image](https://user-images.githubusercontent.com/5052385/203908771-dbc2a27c-b19e-42a8-a953-af13db785627.png)

Карточка появляется в списке пациентов (в жёлтой рамке):
![image](https://user-images.githubusercontent.com/5052385/203909015-3f43d9de-5907-47c7-ae70-a3a2db34d55c.png)

**Comment by flancer64** [comment]
Выложил изменения на live.
