### ISSUE TITLE
Add cache status icon to player

### ISSUE THREAD

**Issue by minkinr** [flancer32/pwa-ra-mob#173]
Александр, 

мне понравился новый подход с иницировнием кеша после нажатия на play. 

Не хватает какого-то маркера-светофора на экране плейра, показывающим статус загузки кеша, (напр рядом с кпокой info или на самой кнопке  play плеера)

Напр, красный не кеширован, желтый грузится, зеленый - загружено.

**Comment by flancer64** [comment]
@minkinr , я сделал рамочку соотв. цветом для изображения в процессе анимации: зелёный, желтый, синий:

![image](https://user-images.githubusercontent.com/5052385/201028376-dfb3ea42-98fa-45a1-afa3-4dc391124d88.png)

Только она изменяет свой цвет в зависимости от статуса кэширования анимации для всего упражнения и статус не обновляется до завершения работы плейера.

**Comment by minkinr** [comment]
Я это увидела,  но рамочка включается только после запуска плеера. А хотелось бы видеть боллее ярко и до начала проигрыша.

**Comment by flancer64** [comment]
Добавил иконку для просмотра состояния кэша анимации для программы (рядом с именем программы):
![image](https://user-images.githubusercontent.com/5052385/201478885-40a136bd-5d54-47e7-92ac-2efb60451cac.png)

По нажатию на иконку открывается диалог для отображения процесса кэширования анимации:
![image](https://user-images.githubusercontent.com/5052385/201478925-d09b3064-e0da-4611-ac6a-9024346e9a25.png)

Если анимация не кэширована (синий), то доступна кнопка добавления в кэш (Создать):
![image](https://user-images.githubusercontent.com/5052385/201478942-f112abea-3957-446b-b9b2-b3640a80b1eb.png)

В процессе кэширования в диалоге отображается текущее состояние:
![image](https://user-images.githubusercontent.com/5052385/201478996-98d354e3-a18e-44e3-98fe-178f36744c35.png)

При завершении процесса становится доступной кнопка удаления кэша (Очистить):
![image](https://user-images.githubusercontent.com/5052385/201479027-c2bfb67c-8bca-4b6e-a50f-427a78a8904c.png)

Выложился на live.

**Comment by flancer64** [comment]
Из настроек убрал просмотр состояния анимации (осталось 3 секции, было 4):
![image](https://user-images.githubusercontent.com/5052385/201479164-9326499d-25db-4ef8-97a2-e02e5adb0fea.png)
