### ISSUE TITLE
Карточка пациента: задержка

### ISSUE THREAD

**Issue by minkinr** [flancer32/pwa-ra-mob#178]
После отправки  упражнения пациенту есть значительная задержка (5мин) перед тем как карточка покажется у врача в  разделе Пациенты.

**Comment by flancer64** [comment]
На данный момент карточка Пациента показывается у Доктора только после того, как Пациент зарегистрируется по указанной ссылке. Я делаю в задаче https://github.com/flancer32/pwa-ra-mob/issues/172 , чтобы в списке Пациентов были видны как существующие пользователи, так и планируемые (ещё неиспользованные приглашения).

**Comment by flancer64** [comment]
@minkinr , на данный момент задержки не должно быть. Карточка пациента доступна у доктора, как только приглашение зарегистрировано на сервере. Возможно, для обновления данных нужно нажать на кнопку "Обновить":


![Image](https://user-images.githubusercontent.com/5052385/203947769-c605b5eb-4bd8-4475-bf89-e04c09dc618f.png)
