### ISSUE TITLE
View assigned programs in patient card

### ISSUE THREAD

**Issue by minkinr** [flancer32/pwa-ra-mob#179]
Хотелось бы при нажатии на карточку пациента, увидеть список назначенных ему программ с датой назначения. Чтобы потом можно бвло зайти в программу и на основе ее составить новую. 

Это большая доработка?

**Comment by flancer64** [comment]
Навскидку - от 2 до 4 часов.

**Comment by flancer64** [comment]
Добавил просмотр назначенных программ из карточки пациента (только для карточек с синим бордюром - остальные ещё не являются пользователями). Из карточки можно клонировать программу пациента:

![image](https://user-images.githubusercontent.com/5052385/205452178-fda99b58-5f63-431e-b823-2eb109c4bbb8.png)

Ещё просится кнопка с удалением программ в список программ. Это уже завтра.

**Comment by flancer64** [comment]
Несколько переработал карточку программы в списке программ (сделал название программы на всю длину карточки) и добавил кнопку удаления:

![image](https://user-images.githubusercontent.com/5052385/205490763-55a60c02-f90a-4b13-b203-3f3d12d63383.png)


Также восстановил слетевший статус кэширования программы (цвета кнопок для кэшированных программ не менялись).
