### ISSUE TITLE
Add share icon to program view screen

### ISSUE THREAD

**Issue by minkinr** [flancer32/pwa-ra-mob#180]
На экране инфо о  программе заменить кнопку "Копировать" на кнопку "три точки"

![20221122_155148.jpg](https://user-images.githubusercontent.com/103753072/203318565-48f7cf88-f535-40ff-9a99-78c4ae0f2b7f.jpg)

**Comment by flancer64** [comment]
@minkinr , я планировал использовать эту иконку (три точки) для обозначения того, что для данного экрана есть дополнительные пункты меню:

![Image](https://user-images.githubusercontent.com/5052385/203804422-2eaefa2e-4656-466a-aaf4-54e21c7bf853.png)

Мы проговаривали, что, если иконок с действиями не более трёх, то мы их выставляем в ряд, если их более 4-х, то выносим две самые популярные в ряд, а остальные сворачиваем в меню, которое открывается как раз по такой иконке (три точки).

Мне кажется, что в предложенном варианте будет конфликт между действиями "копировать программу" и "развернуть дополнительные пункты меню".

**Comment by minkinr** [comment]
Популярная (popular) программа обычно шлется без изменений.  И мне не хватает кнопки "поделиться".Вижу три варианта:1) добавляем "Поделиться" третьей кнопкой2)  добавляем   "три точки" третьей кнопкой 3) убираем кнопку "дублировать" и добавляем вместо нее  "три точки" второй кнопкой.   Про конфликт не поняла. 17:13, 24 ноября 2022 г., Alex Gusev ***@***.***>:
@minkinr , я планировал использовать эту иконку (три точки) для обозначения того, что для данного экрана есть дополнительные пункты меню:

Мы проговаривали, что, если иконок с действиями не более трёх, то мы их выставляем в ряд, если их более 4-х, то выносим две самые популярные в ряд, а остальные сворачиваем в меню, которое открывается как раз по такой иконке (три точки).
Мне кажется, что в предложенном варианте будет конфликт между действиями "копировать программу" и "развернуть дополнительные пункты меню".

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>
-- Отправлено из мобильного приложения Яндекс Почты

**Comment by flancer64** [comment]
Кнопка "Поделиться" для программ у нас доступна только для Докторов. У пациентов есть кнопка "Поделиться" на домашнем экране мобильного приложения.

**Comment by flancer64** [comment]
Кнопку я сделал, но она ведёт на форму для ввода данных по пациенту, а не по выбору данных:
![image](https://user-images.githubusercontent.com/5052385/204328768-68e53349-54a2-40ec-9970-912c134cad23.png)

Пока оставляю так, в задаче [#184](https://github.com/flancer32/pwa-ra-mob/issues/184) буду плотнее работать с этим функционалом, там и замкнусь на новый функционал.
