### ISSUE TITLE
Конструктор:  отправить действующему пациенту

### ISSUE THREAD

**Issue by minkinr** [flancer32/pwa-ra-mob#181]
как поделиться программой со Старым пациентом? 

На кнопке Поделиться вызывается экран добавить Нового пациента.

**Comment by flancer64** [comment]
Пока ещё в стадии доработки - https://github.com/flancer32/pwa-ra-mob/issues/172 На live пока не выкладывал, потому что не доделано.

**Comment by flancer64** [comment]
В основном сделано в рамках #172 . Доработал, чтобы приглашение создавалось сразу при нажатии на "Поделиться", если пациент уже привязан к программе.

**Comment by flancer64** [comment]
Выкладываю на live.
