### ISSUE TITLE
 Mob  глючит при повторной загрузке 

### ISSUE THREAD

**Issue by minkinr** [flancer32/pwa-ra-mob#191]
У меня Mob стал глючить при повторной загрузке. Хорошо грузится только после зачистки кеша или после reinstall PWA

**Comment by flancer64** [comment]
Это связано с https://github.com/flancer32/pwa-ra-desk/issues/67 Я в другом проекте столкнулся с тем, что админка должна работать в разных вкладках в браузере. Пришлось внести изменения в базовый код своей платформы. Я обновил оба ra-приложения, но тут несколько по-другому выполнена авторизация пользователей (клиенты, админы, менеджеры). Поэтому возникла проблема с обновлением ранее установленных пользовательских сессий. Я сейчас над ней работаю. Когда исправлю, корректно заработают сразу и деск, и мобильная часть.

**Comment by flancer64** [comment]
Исправил вместе с https://github.com/flancer32/pwa-ra-desk/issues/67
