### ISSUE TITLE
В mob подсасывается то старое, то новое видео 

### ISSUE THREAD

**Issue by minkinr** [flancer32/pwa-ra-mob#192]
После замены видео на сервере и обновлении desk, в  mob подсасывается то старое, то новое видео. Mob и desk сносила, кеши чистила. Откуда берется старое упражнение непонятно. 

Возможно связанная ошибка:  закешированное  упражнение (зеленое) глючит в плеере.

**Comment by flancer64** [comment]
Мне сложно сказать, как такое может быть - если приложение сносилось полностью, то в нём нет следом от предыдущей инсталляции и всё тянется с сервера. Сервер не кэширует ничего, его не надо рестартовать. Нужно посмотреть, как вы сносили приложения. Как вариант, работает собственный кэш браузера. В этом случае придётся добавлять мета-данные для ограничения времени кэширования на сервер.

**Comment by flancer64** [comment]
Разобрались, во всём виноваты zip-файлы с кадрами. Старое видео показывается при кэшировании анимации. Нужно удалять все каталоги из `/home/ra/store/zip`. Они потом восстановятся уже с новыми архивами.
