### ISSUE TITLE
low priority: второй ракурс 

### ISSUE THREAD

**Issue by minkinr** [flancer32/pwa-ra-mob#193]
Второй ракурс подгружен в карточку desk для упр. зашагивания на ступеньку, но в плеере непонятно, что есть второй ракурс и  как к нему перейти. 

Просто фиксирую. Исправлять пока не надо.

**Comment by flancer64** [comment]
Да, в плейере нельзя увидеть, что есть второй ракурс. Мы тогда (https://github.com/flancer32/pwa-ra-desk/issues/14) сделали структуру данных в базе, чтобы можно было хранить несколько анимаций к одному упражнению, и добавили возможность работать с этим в админке. В плейере берётся первое упражнение из доступных. Доработку плейера оставили "на потом".

**Comment by minkinr** [comment]
поняла. 👌07:45, 3 марта 2023 г., Alex Gusev ***@***.***>:
Да, в плейере нельзя увидеть, что есть второй ракурс. Мы тогда (flancer32/pwa-ra-desk#14) сделали структуру данных в базе, чтобы можно было хранить несколько анимаций к одному упражнению, и добавили возможность работать с этим в админке. В плейере берётся первое упражнение из доступных. Доработку плейера оставили "на потом".

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
-- Отправлено из мобильного приложения Яндекс Почты
