### ISSUE TITLE
Оптимизация  1440:1440:  сейчас или потом?

### ISSUE THREAD

**Issue by minkinr** [flancer32/pwa-ra-mob#194]
Сейчас грузим много видео в формате 1440:1440. Оптимизировать лучше при подготовке фреймов или потом?

**Comment by flancer64** [comment]
Думаю, что можно и потом. Случайных пользователей пока кто не предполагается, а мы знаем, как очищать локальные хранилища браузера, чтобы загрузились новые, оптимизированные версии анимации.
