### ISSUE TITLE
Player не лезет в один экран

### ISSUE THREAD

**Issue by minkinr** [flancer32/pwa-ra-mob#196]
После перехода на квадрат в плеере, изображение немного не лезет в один экран по длине. Сколько времени займёт, чтобы исправить?

**Comment by flancer64** [comment]
Если просто уменьшить изображение, то не много - до получаса с обновлениями. Если редезайнить интерфейс (менять размеры инф. компонентов - счётчка времени, повторений и т.п.), то там уже в часах может идти.

**Comment by minkinr** [comment]
сейчас просто уменьшаем размер

**Comment by flancer64** [comment]
Сейчас получается для квадратных вот так:
![image](https://user-images.githubusercontent.com/5052385/228847372-5cfe05e7-0eaf-4d0c-9a03-c34dc7ed62b7.png)

для прямоугольных так:
![image](https://user-images.githubusercontent.com/5052385/228847557-f5b5af20-ecc6-41ad-befe-919ba51a3f37.png)
