### ISSUE TITLE
Visuals (change icons and colors)

### ISSUE THREAD

**Issue by minkinr** [flancer32/pwa-ra-mob#197]
планирую причесать визуальный обликом. В связи с этим пара вопросов:

- замена иконки и загрузочной заставки  (предполагаю, это менее часа,  если я вам предоставлю готовые, но поправьте меня, если я ошибаюсь);
- замена цвета,  типа весь синий заменить на другой цвет
(это  проблематично или можно в одном месте попроправить? )

**Comment by flancer64** [comment]
Загрузочные заставки и иконки приложения находятся здесь: https://github.com/flancer32/pwa-ra-mob/tree/main/web/img

Вы их и сами можете поменять как пользователь @minkinr . Если вы имеете в виду иконки кнопок, то эти иконки идут из вот этого пакета - https://fonts.google.com/icons На совсем уж произвольные будет поменять не быстро.

Заменить весь синий цвет на другой - скорее всего в одном месте, но могут быть нюансы (отдельные элементы контроля). Но не так, чтобы весь код лопатить, там цвет в стилях зашит.

**Comment by flancer64** [comment]
Попробовал изменить primary-цвет для Quasar UI в стилях. С разбегу получилось вот так:
![image](https://user-images.githubusercontent.com/5052385/228851892-d1f655fb-f13d-4e85-9cf7-09e24fc17ffe.png)

Сейчас по-быстрому гляну, почему кнопки не перекрасились.

Сбалансированные цвета можно брать отсюда: https://www.w3schools.com/colors/colors_monochromatic.asp

**Comment by flancer64** [comment]
Кнопки не перекрасились, потому что у них стиль вычисляется - подсветка текущей "страницы" в нижнем навигаторе. Сейчас вот так:
![image](https://user-images.githubusercontent.com/5052385/228857158-88eccf21-c756-48a4-8843-46673d16318b.png)

**Comment by flancer64** [comment]
С цветами у меня полный бардак. По-хорошему, цвета нужно кодироват на уровне стилей (CSS) и употреблять в классах или стилях кода в виде переменных. Переменные нужно держать в файлах:
* `web/css/vars.css`: здесь задаются имена переменных и их значения;
* `src/Front/Defaults.mjs`: в константах типа `COLOR_*` идёт привязка js-кода к именам css-переменных;

Я сейчас структуру заложил, основной цвет (`primary`) можно менять здесь (https://github.com/flancer32/pwa-ra-mob/blob/main/web/css/vars.css#L21):
```css
:root {
    /*--q-primary: var(--color-set-base);*/
    ...
}
```

Если убрать комментарии, то основным (primary) будет фиолетовый цвет (код задан в переменной `--color-set-base`):
```css
:root {
    --q-primary: var(--color-set-base);
    ...
}
```
Переменные я разнёс специально, чтобы монохроматические цвета не смешивались с переменными Quasar UI.

**Comment by flancer64** [comment]
Можно по-быстрому менять цвет прямо на сервере:
* `/home/ra/inst/mob/web/css/var.css`

**Comment by minkinr** [comment]
Александр,  перед загрузкой экрана с шарами появляется экран с кактусом на чёрном фоне. это какой-то атавизм.

**Comment by flancer64** [comment]
@minkinr вы сейчас про загрузку на каком устройстве говорите? Если на мобильном, то это иконка для PWA. Нужно делать различные размеры для иконки и выкладывать сюда: 
* https://github.com/flancer32/pwa-ra-mob/blob/main/web/img/favicon-192.png
* https://github.com/flancer32/pwa-ra-mob/blob/main/web/img/favicon-512.png
* https://github.com/flancer32/pwa-ra-mob/blob/main/web/favicon.ico

Цвет фона загрузочного экрана и цвет фона приложения (темы) задаётся в манифесте: 
* https://github.com/flancer32/pwa-ra-mob/blob/main/web/manifest.json#L2
* https://github.com/flancer32/pwa-ra-mob/blob/main/web/manifest.json#L21

**Comment by flancer64** [comment]
И эти иконки там уже очень давно, с 10 октября прошлого года.

**Comment by flancer64** [comment]
Даже раньше. 10-го октября это я репо чистил и всё в новый репозиторий переносил.

В общем, какие-то картники там должны быть - это требование технологии. Если не подходят эти, дайте мне другую картинку форматом 512x512 и я заменю те, что есть.

**Comment by minkinr** [comment]
1) Основной цвет приложения #006666

2.1) Загрузочный экран 512 на прозрачном фоне приложен
![заставка_transparent_512](https://user-images.githubusercontent.com/103753072/229309833-ac789d14-664f-42ca-af81-f04c78bdb0c4.png) 
2.2) надо добавить фон заливки #006666
2.3) Шары убираем, а процент загрузки оставляем на загрузочном экране

3) Иконка приложения .ico сюда не грузиться. Прямо в код я побоялась добавить. Сброшу вам в телеграмм. Вариант в png 512 и 192  прикладываю:
![ящерка для иконки 192](https://user-images.githubusercontent.com/103753072/229310331-8564b15f-9e22-473e-9414-b54eb239b630.png)
![ящерка для иконки 512](https://user-images.githubusercontent.com/103753072/229310333-b7331c45-c51c-4e83-9976-c0e07e8d2d09.png)

**Comment by flancer64** [comment]
@minkinr , а вот эта синяя точка в центре - это так надо или её лучше убрать?

![image](https://user-images.githubusercontent.com/5052385/229332417-edbd6e77-9629-4281-aafc-e749fc4d8c8d.png)

**Comment by flancer64** [comment]
Готово, выложил на live и mob, и desk.

**Comment by minkinr** [comment]
ой, это ошибка, надо убрать.

вс, 2 апр. 2023 г., 08:03 Alex Gusev ***@***.***>:

**Comment by flancer64** [comment]
Убрал. Сейчас вот так:
![image](https://user-images.githubusercontent.com/5052385/229338435-01f1de9b-88ab-4d47-ad48-bbe1aae0d9aa.png)

**Comment by flancer64** [comment]
Нужно прозрачную картинку поставить на начальный экран. Там белым ящерка нарисована.

**Comment by flancer64** [comment]
Выложил на live, теперь так:
![image](https://user-images.githubusercontent.com/5052385/229742074-557728b3-bfc1-4609-95f0-e6e5554f6a36.png)
