### ISSUE TITLE
Карточка упражнения в desk

### ISSUE THREAD

**Issue by minkinr** [flancer32/pwa-ra-mob#198]
Текущее поле "Примечание" - использовать под одно из полей ниже (или переназвать?)

Нужны поля:

1) "Источник", привязанное к клинике

2) "Примечание" текстовое

3) "English Title" текстовое. Записи делались в "Примечание".  В идеале сохранить уже сделанные записи. 

В идеале сделать "English Title" searchable в desk и желательно в mob.

**Comment by flancer64** [comment]
Тут с изменением структуры данных в БД и с миграцией. Скорее всего в районе 4 часов. Причём без searchable. Это отдельная задача - там нужно ещё часа полтора-два.
