### ISSUE TITLE
Пока не делаем: новый формат Player'a ?

### ISSUE THREAD

**Issue by minkinr** [flancer32/pwa-ra-mob#204]
Мысли вслух. Чтобы оптимизировать место возможно стоит кнопки плеера сделать всплывающими во время паузы на картинке  (назад слева, плей по центру,вперед справа).  Подходы и повторы изобразить точками.

**Comment by flancer64** [comment]
@minkinr , мне по этой задаче делать что-либо?

**Comment by minkinr** [comment]
пока нет18:08, 9 октября 2023 г., Alex Gusev ***@***.***>:
@minkinr , мне по этой задаче делать что-либо?

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>
-- Отправлено из мобильного приложения Яндекс Почты
