### ISSUE TITLE
Цвет меняющихся иконок

### ISSUE THREAD

**Issue by minkinr** [flancer32/pwa-ra-mob#205]
![Снимок экрана 2023-04-19 155539](https://user-images.githubusercontent.com/103753072/233094073-f26367f8-5e4d-4a4a-8508-48bfd2f961c0.png)
 
Выделеные красным кнопки пока программа незгружена должны быть цвета #ffdfbd. После загрузки они должны  становиться дефолтного цвета #006666. 

Делаем.

**Comment by flancer64** [comment]
Стало так: 
![image](https://user-images.githubusercontent.com/5052385/233290311-9c3ce60b-7a1c-4fd1-b6e6-49557663baae.png)

**Comment by flancer64** [comment]
Выложился на live.
