### ISSUE TITLE
bugs: регистрация

### ISSUE THREAD

**Issue by minkinr** [flancer32/pwa-ra-mob#206]
Пишу для памяти. Наверно пока ничего делать не надо. 

Знакомый регистрировался с apple. У него были затруднения: 

1) При регистрации пришлось несколько раз повторить, так как вместо email a, высвечивается какая то  default-ная запись, точно не помню какая. Пока нет возможности ответить на другом телефоне. 
2) После регистрации логично было бы сразу войти, но этого не происходит, нужно ещё раз войти. 
3) Иконка сама не поставилась, ставили принудительно.

**Comment by flancer64** [comment]
Если есть возможность, то было бы хорошо делать скриншоты с багами.

**Comment by minkinr** [comment]
это был real-life case. не было возможности. когда добу iPhone попробую воспроизвести и прислать16:49, 26 мая 2023 г., Alex Gusev ***@***.***>:
Если есть возможность, то было бы хорошо делать скриншоты с багами.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
-- Отправлено из мобильного приложения Яндекс Почты

**Comment by minkinr** [comment]
С телефона мужа -проблемы 1-2) воспроизвести не удалось. Пункт 3 есть.

**Comment by minkinr** [comment]
@flancer64 

Воспроизвелась проблем на android. 

Когда врач посылает программу пациенту. у того возникает приложенный экран . Вместо email написано true.

**Comment by flancer64** [comment]
> Иконка сама не поставилась, ставили принудительно.

В iphone нет такой поддержки PWA, как в Android. Там нужно вручную устанавливать иконку на экран мобильника.

Про true и автоматический вход - буду делать завтра.

**Comment by flancer64** [comment]
Исправил, выложил на live.

**Comment by minkinr** [comment]
Тестировала с заходом по ссылке. Теперь вообще не заходит. 

![Image](https://github.com/flancer32/pwa-ra-mob/assets/103753072/4a1a3e24-28ef-4654-94ac-561d6f9b1628)

**Comment by flancer64** [comment]
Надо нажать на кнопку ¨Reinstall PWA¨. Скорее всего, у вас в браузере осталась старая версия приложения, а на сервере уже новая. Эта кнопка появляется, если загрузка приложения не завершилась в заданное время.

**Comment by flancer64** [comment]
По ссылке https://mob.rehapp.ru/#/user/sign/up/72d04d6b-f5cc-43e2-b42c-9ff693b4dfc7 мне удалось открыть форму регистрации. Но я всегда чищу браузер, когда изменяю проект.

![image](https://github.com/flancer32/pwa-ra-mob/assets/5052385/93e15754-3550-47d4-b964-ed186c59133c)

**Comment by minkinr** [comment]
> Надо нажать на кнопку ¨Reinstall PWA¨. Скорее всего, у вас в браузере осталась старая версия приложения, а на сервере уже новая. Эта кнопка появляется, если загрузка приложения не завершилась в заданное время.

Приложение сносила полностью перед нажатием на ссылку. 
Reinstall PWA нажимала - ноль эмоций. 
Повторилось одно и то же 2 раза.

**Comment by flancer64** [comment]
Какой браузер?

**Comment by flancer64** [comment]
Попробуйте нажать Ctrl+Alt+N (анонимная сессия), после чего перейти по ссылке выше. Если не получится, то нам нужно будет связаться, когда будет такая возможность, чтобы я удалённо посмотрел, какие ошибки вылетают.

**Comment by minkinr** [comment]
а на телефоне? android - chrome08:50, 30 мая 2023 г., Alex Gusev ***@***.***>:
Попробуйте нажать Ctrl+Alt+N (анонимная сессия), после чего перейти по ссылке выше. Если не получится, то нам нужно будет связаться, когда будет такая возможность, чтобы я удалённо посмотрел, какие ошибки вылетают.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you modified the open/close state.Message ID: ***@***.***>
-- Отправлено из мобильного приложения Яндекс Почты

**Comment by flancer64** [comment]
На телефоне в андроиде нужно очистить кэш и внутренние хранилища для конкретного приложения. Для iphone нужно специальный скрипт писать для очистки всего. Он отдельно для приложения или сайта не делает чистки, насколько мне известно.

**Comment by minkinr** [comment]
это делала

вт, 30 мая 2023 г., 09:04 Alex Gusev ***@***.***>:

**Comment by flancer64** [comment]
Только что проверил на своём телефоне - [ссылка](https://mob.rehapp.ru/#/user/sign/up/72d04d6b-f5cc-43e2-b42c-9ff693b4dfc7) открывается. Попробуйте сделать uninstall приложения и зайти по ссылке.

**Comment by minkinr** [comment]
Сейчас все сработало. Видимо вчера когда делала что-то ещё не обновилось. Закрываем. 09:10, 30 мая 2023 г., Alex Gusev ***@***.***>:
Только что проверил на своём телефоне - ссылка открывается. Попробуйте сделать uninstall приложения и зайти по ссылке.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you modified the open/close state.Message ID: ***@***.***>
-- Отправлено из мобильного приложения Яндекс Почты
