### ISSUE TITLE
Правки: Конструктор-Редактирование упражнения

### ISSUE THREAD

**Issue by minkinr** [flancer32/pwa-ra-mob#207]
1) На экране Конструктора-Редактирование упражнения картинка упражнения  выглядит огромной (на весь экран на компе и 50% в телефоне). Надо уменьшить в 3 раза.
2) Маркер На каждую сторону сделать невидимым. Он ни  к чему не приводит и поэтому дезориентирует.
![Снимок экрана 2023-06-14 160154](https://github.com/flancer32/pwa-ra-mob/assets/103753072/43ec2e5e-a5a9-4a05-86ee-a1aa322f12e9)

**Comment by flancer64** [comment]
Похоже, что это компонент `Ra_Mob_Front_Ui_Lib_Exrc_Edit`, в котором используется компонент `Ra_Mob_Front_Ui_Lib_Exrc_Image`. Этот компонент анимирует упражнение, маркер (рамка) отображает статус анимации (кэширована в памяти устройства или нет).

Ограничения по размеру для изображения заложены в CSS и рассчитаны на воспроизведение упражнения:
```
.ra-player .ra-anime-img {
    border-radius: 8px;
    height: min(100%, 90vh, 400px);
    width: min(100%, 60vw, 400px);
}
```

ОК, я сделаю ограничение размера в 3 раза для режима редактирования и сделаю цвет рамки конфигурируемым - чтобы можно было отключать подсветку для режима редактирования. @minkinr , если цвет рамки вообще нигде не нужен в качестве маркера, то я могу вообще удалить этот функционал из приложения.

**Comment by minkinr** [comment]
цвет рамки не нужен

**Comment by minkinr** [comment]
Под-пункт 1 сделан. На телефоне отлично. Комп допроверю. 

Под-пункт 2  надо сделать "Маркер На каждую сторону сделать невидимым. Он ни к чему не приводит и поэтому дезориентирует."

**Comment by flancer64** [comment]
Всё, я понял. "На каждую сторону" - вот это маркер. А я посчитал, что маркер - это цвет рамки, которая показывается во время анимации изображения и отображает статус кэширования. Я её и убрал.

> если цвет рамки вообще нигде не нужен в качестве маркера, то я могу вообще удалить этот функционал из приложения.

OK, удалю это поле ("На каждую сторону") с UI. Но оно у нас прокинуто через весь API до самой базы. Полагаю, нужно сделать по-быстрому - закрыть в UI и оставить во всём остальном. Или делать "как положено" - с полной очисткой этого поля из приложения? Разница в трудозатратах - порядок минимум.

**Comment by minkinr** [comment]
Пока по-быстрому.

Чистку можем зафиксировать в бэклог.

ср, 21 июн. 2023 г., 06:38 Alex Gusev ***@***.***>:

**Comment by flancer64** [comment]
Выложился на live. Стало так:

![Image](https://github.com/flancer32/pwa-ra-mob/assets/5052385/05129f38-97ac-4535-b3ed-4641a614db85)
