### ISSUE TITLE
Конструктор - Запинить галку (Save) в экранах Добавить упражнение и Редактирование упражнения.

### ISSUE THREAD

**Issue by minkinr** [flancer32/pwa-ra-mob#208]
Если доделка <1 часа, хорошо бы закрепить (pin) верхнюю строчку или хотя бы просто галочку, чтобы не уезжала при прокрутке экрана. 
![Снимок экрана 2023-06-14 161832](https://github.com/flancer32/pwa-ra-mob/assets/103753072/520d23d5-0ec8-4f37-9ea1-034d5cf0aa10)

**Comment by flancer64** [comment]
Закрепил панель инструментов, но есть вот такие эффекты - когда иконки упражнений находятся над панелью:

![image](https://github.com/flancer32/pwa-ra-mob/assets/5052385/0540a06e-ef3c-4256-ba1d-514acbdd9a59)

**Comment by flancer64** [comment]
Исправил, выкатился на live.
![image](https://github.com/flancer32/pwa-ra-mob/assets/5052385/de3b4ea2-fd50-4a7d-98a1-4dab6f5d489f)

**Comment by flancer64** [comment]
Да, точно. Я сделал только для экрана выбора упражнений для добавления в программу. Сделал отдельный UI-компонент  (`Ra_Mob_Front_Ui_Lib_Sticky`) и добавил на экраны просмотра списка программ, редактирования и просмотра программы, редактирования упражнения.

Выложил на live.

**Comment by minkinr** [comment]
Проверила. Отлично
