### ISSUE TITLE
Не работает функция "Сбросить пароль"

### ISSUE THREAD

**Issue by minkinr** [flancer32/pwa-ra-mob#226]
1) При нажатие на "Забыли пароль?"-》 "Сбросить" форма показывает крутящиеся шестерёнки и ничего дальше не происходит. 
 
2) Заменить названия: 
2.1 Название формы "Сбросить пароль" заменить на "Восстановление пароля" 
2.2 Название кнопки "сбросить" заменить на "восстановить"

**Comment by flancer64** [comment]
Исправил, выкатил на live:
![image](https://github.com/flancer32/pwa-ra-mob/assets/5052385/b41e6364-a8a6-468d-9b99-2f8c2716370a)
