### ISSUE TITLE
Проблемы с воспроизведением упражнений

### ISSUE THREAD

**Issue by flancer64** [flancer32/pwa-ra-mob#227]
Сообщение от клиента:

> Записал видео: буквально пару упражнений, но тут очень наглядно. Второе упражнение вообще “замерзло“ на исходном положении

**Comment by flancer64** [comment]
Вот видео проблемы:

https://github.com/flancer32/pwa-ra-mob/assets/5052385/564cc557-5a61-42c8-a47a-c1e3e751d165

**Comment by flancer64** [comment]
@minkinr , для начала было бы хорошо этому пользователю переустановить полностью своё приложение. Это как раз тот пользователь, которому мы меняли роль с Пациента на Доктора. Т.к. на видео экран смартфона, то я не думаю, что он переустанавливал приложение после смены роли. На смартфонах не так-то просто удалить/поставить приложение, как на десктопах.

**Comment by minkinr** [comment]
Ок. Попрошу его переставить. Та же проблема была у него и до смены роли.

**Comment by minkinr** [comment]
Вы делали кнопку в настройках "удалить приложение" - этого недостаточно?

**Comment by flancer64** [comment]
> Вы делали кнопку в настройках "удалить приложение" - этого недостаточно?

Да, этого должно хватить. По ней зачищаются внутренние хранилища данных в браузере.

**Comment by flancer64** [comment]
Запустил на воспроизведение программу 12 (судя по видео, это она). На втором упражнении было смешение кадров из разных анимаций:
![001](https://github.com/flancer32/pwa-ra-mob/assets/5052385/3a9c114a-401a-46c2-a9bb-58c3a15da8f3)

и

![001](https://github.com/flancer32/pwa-ra-mob/assets/5052385/ea98f59f-565e-4f0f-b03d-1729164c0884)

Зачистил zip'ы с кадрами (серверный кэш).

**Comment by flancer64** [comment]
Обнаружил, что при воспроизведении второго упражнения в программе (дальше я не заходил) анимация не воспроизводится на первом повторе первого подхода. Попробую воспроизвести локально.

**Comment by flancer64** [comment]
Смена кадров анимации на демонстрационном видео с ошибками видна на 2:07.

В общем, похоже, что тут несколько ошибок накладывается друг на друга. Кэширование кадров и замораживание анимации на первом круге. Буду копать...

**Comment by flancer64** [comment]
@minkinr , может есть смысл добавить action (действие) в карточку упражнения в админке для зачистки конкретного zip'а с анимацией (серверный кэш)? Или даже можно действие для зачистки всех zip'ов поставить на грид с упражнениями. Или на зачистку и регенерацию всех zip'ов. Это так, предложение на будущее. Если будет активная работа с кадрами анимации упражнений. Проще, конечно, удалять архивы с кадрами анимации вручную из файловой системы, но так же просто можно удалить совсем не то.

Кстати, если пользователь загрузил в кэш браузера один вариант анимации, а потом она на сервере поменялась на другой, то пользователь может и не увидеть новой версии, пока не сбросит кэш у себя.

**Comment by flancer64** [comment]
Да, у меня в плейере была ошибка, когда при смене упражнения после завершения последнего повтора в последнем подходе для текущего упражнения и переходе к следующему в L2-кэш не загружались кадры анимации для следующего упражнения.

**Comment by minkinr** [comment]
Александр, 

мне нравиться предложенный action. вы могли бы прикинуть по часам доработки?

> @minkinr , может есть смысл добавить action (действие) в карточку упражнения в админке для зачистки конкретного zip'а с анимацией (серверный кэш)? Или даже можно действие для зачистки всех zip'ов поставить на грид с упражнениями. Или на зачистку и регенерацию всех zip'ов. Это так, предложение на будущее. Если будет активная работа с кадрами анимации упражнений. Проще, конечно, удалять архивы с кадрами анимации вручную из файловой системы, но так же просто можно удалить совсем не то.
> 
> Кстати, если пользователь загрузил в кэш браузера один вариант анимации, а потом она на сервере поменялась на другой, то пользователь может и не увидеть новой версии, пока не сбросит кэш у себя.

**Comment by flancer64** [comment]
> вы могли бы прикинуть по часам доработки?

Навскидку, получается 1-2 часа. С регенерацией всех zip'ов  - может быть 3, если будут какие-то проблемы.

**Comment by minkinr** [comment]
делаем

вт, 5 сент. 2023 г., 16:47 Alex Gusev ***@***.***>:

**Comment by flancer64** [comment]
Выложил изменения на пилота и live. На live почистил серверный кэш (zip'ы).
