### ISSUE TITLE
Кабинет врача: новый врач - старый пациент

### ISSUE THREAD

**Issue by minkinr** [flancer32/pwa-ra-mob#229]
Сейчас тестировала ситуацию, когда врач назначает программу пациенту, который есть в базе, но отсутствует у данного врача. 
Получается такому пациенту назначить программу невозможно. Пациент просто не ставится. Могу запись экрана прислать.

В клиниках с несколькими врачами такая ситуация бывает.  

Это не высокий приоритет . Посмотрите при возможности.

**Comment by flancer64** [comment]
Это так и было заложено, насколько я помню. Врач видит только своих пациентов. Чтобы персональные данные не утекали. По-моему мы как-то проговаривали возможность просмотра всех пациентов всех врачей одной клиники, но там реализация уже не совсем простая - в пару часов не уложиться (4-8 на первый взгляд). Поэтому и не делали.

**Comment by minkinr** [comment]
Да, помню про персональные данные. Это правильно, что данные не шарятся. 
Только как-то неправильно, что врач не может такого пациента внести в программу. По идее, когда пациент сказал свой емейл второму врачу и тот его внес как нового пациента, то доступ к этому пациенту для врача  должен открыться?

**Comment by flancer64** [comment]
Мы клиники внесли в приложение по ходу дела, как контактные данные (типа телефона). А чтобы у врачей одной клиники был общий доступ ко всем пациентам всех врачей этой клиники, нужно дорабатывать функционал. Мы во время митинга слегка затронули вопросы миграции клиентов/докторов (например, смена доктором клиники или клиентом доктора) и не стали копать в этом направлении - просто оставили клиники в качестве контактных данных (кодификатора - поэтому и отдельная таблица и возможность добавления через админку). Причём даже в карточке доктора в админке не выводится эта информация. Клиника привязывалась менеджером на момент создания в админке приглашения для доктора.

В общем, там такой пласт связанных вопросов начинает тянуться, в том числе и с тем "чей пациент?", что мы просто внесли клиники в структуру данных на будущее и дальше сильно не двинулись.

**Comment by flancer64** [comment]
> По идее, когда пациент сказал свой емейл второму врачу и тот его внес как нового пациента, то доступ к этому пациенту для врача должен открыться?

В структуре у нас заложена множественная связь "пациент-доктор", т.е. один пациент может быть привязан ко множеству докторов. Насколько я помню, если доктор назначил пациенту программу и пациент вошёл в приложение под существующей учёткой, то устанавливается новая связь между пациентом и доктором (должна, по крайней мере). Самостоятельно доктор пациентов себе добавить не может - только через назначение программы. А там уже зависит от того, под какой учёткой пациент примет приглашение - с тем же email'ом или другим. Если вы помните, то в списке пользователей у доктора записи выделялись разным цветом - пользователи и приглашения (ещё не принятые назначения программ).
