### ISSUE TITLE
Конструктор: детали упражнения в списке

### ISSUE THREAD

**Issue by minkinr** [flancer32/pwa-ra-mob#230]
Показывала программу врачу и получила такую обратную связь. 

Врачу не удобно заходить каждый раз в редактирование, чтобы проверить настройки упражнения, поэтому хотелось бы иметь базовую инфо на этом экране (выделено красным) 

![Screenshot_20230907_141906_Chrome.jpg](https://github.com/flancer32/pwa-ra-mob/assets/103753072/5e65e95e-1e11-4b88-bdf2-f7567ba57d2e)

**Comment by flancer64** [comment]
Получается как-то так:
![image](https://github.com/flancer32/pwa-ra-mob/assets/5052385/dd22157c-457c-44d8-b29d-02616e80f3c2)

**Comment by flancer64** [comment]
Выложился на live & pilot
