### ISSUE TITLE
Структурируем экран Программы

### ISSUE THREAD

**Issue by minkinr** [flancer32/pwa-ra-mob#234]
Структурируем экран программы. Хорошо бы добавить раскрывающиеся списки): 
- назначенные (сверху), более свежие выше. 
- мои (в середине) 
- популярные (снизу)
- типовые (еще ниже; у базовых пациентов типовые скрыть, а у врача и продвинутых пациентов они будут). 

![Screenshot_20230908_170828_Chrome.jpg](https://github.com/flancer32/pwa-ra-mob/assets/103753072/035aae8c-6e84-4e60-b0a6-a9eccfed138e)

**Comment by flancer64** [comment]
![image](https://github.com/flancer32/pwa-ra-mob/assets/5052385/a432a501-6913-4d33-bee5-d7361e49d820)

![image](https://github.com/flancer32/pwa-ra-mob/assets/5052385/9abd13cd-1398-4edd-99ee-bb929262af7a)

**Comment by flancer64** [comment]
Выложился на live вместе с #228

**Comment by minkinr** [comment]
Александр, @flancer64 , в целом все отлично. Единственное, у базовых пациентов Типовые программы должны быть залочены (скрыты).

**Comment by flancer64** [comment]
> Единственное, у базовых пациентов Типовые программы должны быть залочены (скрыты).

У-упс... я, походу, залочил их для [Промо-пациентов](https://github.com/flancer32/pwa-ra-mob/commit/4e06ecb1fac47375bc7518ea7d2225438fc52b6c#diff-d473ad7261e57d24cd69efb39531dc748a9769546707733c4faf5729b07cca1dR140). Исправлю.

**Comment by flancer64** [comment]
Исправил. Выложил на live & pilot.
