### ISSUE TITLE
Добавить в Контакты email 

### ISSUE THREAD

**Issue by minkinr** [flancer32/pwa-ra-mob#235]
Добавить в Контакты email - rehapp.manager@yandex.ru

**Comment by flancer64** [comment]
Сделал так:
![image](https://github.com/flancer32/pwa-ra-mob/assets/5052385/fe145cb7-c639-4c75-903f-05936e9c05f9)


При нажатии на кнопку открывается ссылка `mailto:rehapp.manager@yandex.ru`. В мобильном устройстве предлагается выбрать почтовый клиент:
![image](https://github.com/flancer32/pwa-ra-mob/assets/5052385/cd91ba3c-ff9e-4c50-8ff0-3593f2ef6b57)

**Comment by minkinr** [comment]
на что на компе ?12:27, 20 сентября 2023 г., Alex Gusev ***@***.***>:
Сделал так:

При нажатии на кнопку открывается ссылка ***@***.*** В мобильном устройстве предлагается выбрать почтовый клиент:


—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
-- Отправлено из мобильного приложения Яндекс Почты

**Comment by flancer64** [comment]
Добавил, чтобы в письмо автоматом вставлялся subject: `Mail from ReHab (${user.name})`

**Comment by flancer64** [comment]
> на что на компе ?

Зависит от настроек компа. Если есть обработка ссылок типа `mailto`, то откроется mail-клиент. Если нет - то откроется новая пустая страница с адресом в заголовке:

![image](https://github.com/flancer32/pwa-ra-mob/assets/5052385/ef24e6a9-8076-4a54-87bc-a9d791a54d41)

**Comment by minkinr** [comment]
Давайте так: 

![Screenshot_20230920_124935_Chrome.jpg](https://github.com/flancer32/pwa-ra-mob/assets/103753072/164684a2-b7df-40b3-911d-5cb4198fe5cb)
