### ISSUE TITLE
Добавить статистику включения программ в карточку пациента у врача (Light)

### ISSUE THREAD

**Issue by minkinr** [flancer32/pwa-ra-mob#236]

**Comment by flancer64** [comment]
Доктор должен иметь возможность смотреть статистику только для тех пациентов, с которыми у него есть отношения. Если доктор назначает программу пациенту, то такая программа имеет в атрибуте `owner_ref` идентификатор пациента. Этот же идентификатор должен быть свяазнным с идентификатором самого доктора в таблице `app_user_ref_dp`.

**Comment by flancer64** [comment]
Вот такая картинка выходит:
![image](https://github.com/flancer32/pwa-ra-mob/assets/5052385/b2d98255-8fda-4363-990e-e91e50dc9030)

**Comment by flancer64** [comment]
Статистику для клиента сделал аналогично:
![image](https://github.com/flancer32/pwa-ra-mob/assets/5052385/228d4238-325b-4b6d-8b76-a7678cb2dce4)

**Comment by flancer64** [comment]
Выложился на live.
