### ISSUE TITLE
Email попадает в спам

### ISSUE THREAD

**Issue by minkinr** [flancer32/pwa-ra-mob#238]
Александр, взгляните на статью. Есть для нас что-то полезное?
Может нам сделать рассылку с корпоративной почты на яндексе? 
https://dzen.ru/a/X8TG-mPVdAQVNEtz

**Comment by flancer64** [comment]
В статье есть ссылка на валидацию отправителя. Попробовал отправить приглашение на их тестовый email. Вот результат:


![Image](https://github.com/flancer32/pwa-ra-mob/assets/5052385/a0af4103-9571-446d-82ce-2eaee566856e)

**Comment by flancer64** [comment]
Вот детализация по SpamAssassin:


![Image](https://github.com/flancer32/pwa-ra-mob/assets/5052385/1d3ef46c-b637-4ab0-b6dc-0b87a6f307dc)

**Comment by flancer64** [comment]
Тут ничего нельзя сделать:
![image](https://github.com/flancer32/pwa-ra-mob/assets/5052385/8611d312-328f-4312-9435-b86af4a8ac20)

1) Это адрес гугловского сервера.
2) Ссылка работает, я проверял с российского сервера. Значит тестовая программа по каким-то причинам не может открыть ссылку.

**Comment by flancer64** [comment]
![image](https://github.com/flancer32/pwa-ra-mob/assets/5052385/e7c88bea-1d00-43f1-a0cf-56258ec40578)

Можно попробовать добавить заголовок к письму и сделать HTML-формат.

**Comment by flancer64** [comment]
Добавил текстовую версию письма - поднял оценку до 9/10. Выкладываюсь на live.

**Comment by flancer64** [comment]
Выложился на live. @minkinr , можно попробовать на реальном email'е - пройдёт спам-фильтр или нет.

**Comment by minkinr** [comment]
Отправила с test.doc@ya.ru на minkinr@yandex.ru 

Вообще не дошло.

**Comment by minkinr** [comment]
Отправляла с test.doc@ya.ru на minkinr@yandex.ru.  Дошло. Ура!
