### ISSUE TITLE
Обсуждение: убрать кнопку очистить. 

### ISSUE THREAD

**Issue by minkinr** [flancer32/pwa-ra-mob#239]
Я уже 2 раза при открытии этого экрана нажимала на очистить, когда хотела просто закрыть. 

Предлагаю убрать кнопку "очистить". 

![Screenshot_20230919_102557_Chrome.jpg](https://github.com/flancer32/pwa-ra-mob/assets/103753072/66f17e37-ae6f-41ab-b792-7070f7ccb220)

**Comment by flancer64** [comment]
Если убрать кнопку, то у пользователя пропадает возможность удалить с телефона большой объём закэшированных данных (анимация). С моей точки зрения лучше было бы добавить кнопку "ОК" или "Закрыть".

**Comment by minkinr** [comment]
Вижу 2 варианта:кнопка закрыть яркая, кнопка очистить прозрачная12:05, 20 сентября 2023 г., Alex Gusev ***@***.***>:
Если убрать кнопку, то у пользователя пропадает возможность удалить с телефона большой объём закэшированных данных (анимация). С моей точки зрения лучше было бы добавить кнопку "ОК" или "Закрыть".

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
-- Отправлено из мобильного приложения Яндекс Почты

**Comment by minkinr** [comment]
@flancer64 ,  а может лучше зачищать кеши через настройки-приложение-зачистить кеш (возможно по программам)? По упражнению зачищать кеш не очень эффективно. ЧТо думаете?

**Comment by flancer64** [comment]
В данном диалоге удаляется кэш для всех упражнений в программе. Добавить дополнительную кнопку для "Закрыть" будет на порядок быстрее. К тому же логично иметь очистку кэша в том же месте, где и его создание.

**Comment by flancer64** [comment]
С разноцветными кнопками получается так:
![image](https://github.com/flancer32/pwa-ra-mob/assets/5052385/f7ee9f2e-3ffb-494a-b5e3-498a5f7135bd)

**Comment by flancer64** [comment]
Оставляю с кнопками в цвет текущего состояния кэша:
![image](https://github.com/flancer32/pwa-ra-mob/assets/5052385/5b1ecc35-11ac-4a9e-869b-3db0435f4711)

**Comment by flancer64** [comment]
Выложил на live.

**Comment by minkinr** [comment]
Лучше с разноцветными кнопками.

чт, 28 сент. 2023 г., 12:16 Alex Gusev ***@***.***>:

**Comment by flancer64** [comment]
Так?

![Image](https://github.com/flancer32/pwa-ra-mob/assets/5052385/45545d41-8f12-420c-affe-122528b513f1)

**Comment by flancer64** [comment]
Выложил с красной кнопкой на live.
