### ISSUE TITLE
Срочно: после редактирования программы не реагирует на кнопку <- назад. 

### ISSUE THREAD

**Issue by minkinr** [flancer32/pwa-ra-mob#241]
после редактирования программы и нажатия на Save (V) не реагирует на кнопку <- назад. Выйти никуда не возможно.

**Comment by flancer64** [comment]
Проверил - не воспроизводится.

* вошёл как доктор
* открыл экран списка программ
* выбрал программу "Тенодез бицепса, неделя 1-4 (проект)" из секции "Мои" и нажал на иконку "Редактировать"
* исправил название и нажал Сохранить
* после нажатия на кнопку "Назад" перехожу на список программ.

**Comment by flancer64** [comment]
По кнопке "Назад" происходит возврат на предыдущую страницу (`this.$router.back()`). Я даже зашёл по прямой ссылке в режим редактирования и нашал "Назад" - произошёл переход на пустую страницу браузера. Все проверки делал в Хроме на десктопе.

@minkinr , мне нужно больше информации для воспроизведения ошибки.

**Comment by flancer64** [comment]
Как вариант, можно добавить в список действий переход на список программ:
![image](https://github.com/flancer32/pwa-ra-mob/assets/5052385/9ccfe68a-7393-4b01-8927-551848f75303)

**Comment by flancer64** [comment]
Добавил действие "Список программ", выкладываю на live.

**Comment by flancer64** [comment]
Продолжаем вести наблюдение.
