### ISSUE TITLE
Изучение вопроса: Плеер: зазеркаливание левой стороны

### ISSUE THREAD

**Issue by minkinr** [flancer32/pwa-ra-mob#243]

**Comment by flancer64** [comment]
В CSS есть такая инструкция:
```css
transform: scaleX(-1);
```

которая выполняет зеркалирование для изображения. Можно всё сделать средствами браузера. Это совсем просто.

**Comment by flancer64** [comment]
Есть проблема с зеркалированием упражнений при выводе программы на печать. Зеркальные упражнения не отображаются:
[ra_prg_579.pdf](https://github.com/flancer32/pwa-ra-mob/files/12724817/ra_prg_579.pdf)

**Comment by flancer64** [comment]
Обнаружил ошибку в коде - при первом повторе в подходе закэшированная анимация не воспроизводится.

**Comment by flancer64** [comment]
Выложил зеркалирование на live.

**Comment by flancer64** [comment]
> Обнаружил ошибку в коде - при первом повторе в подходе закэшированная анимация не воспроизводится.

Второй повтор в подходе тоже не анимируется?

**Comment by minkinr** [comment]
Оба не работают

**Comment by flancer64** [comment]
Я имею в виду вот эту задачу - #245. Когда запускается анимация, то первый повтор в каждом подходе не анимируется. Я только что проверил live - начиная со второго подхода анимация отрабатывает.

**Comment by minkinr** [comment]
Да, верно , второй повтор работает. Я в первый раз неправильно поняла вопрос.
