### ISSUE TITLE
Вопрос: все упр для doc@gmail.com

### ISSUE THREAD

**Issue by minkinr** [flancer32/pwa-ra-mob#244]
@flancer64 , возможно ли, чтобы для только для врача doc@gmail.com были доступны все упражнения, включая непубличные? 
Это было удобно при разработке новых программам. 

Если да, то оцените, пожалуйста,  часы.

**Comment by flancer64** [comment]
Да, возможно. До часа если все видят только публичные, а doc видит и публичные, и непубличные тоже.

**Comment by minkinr** [comment]
отлично, делаем.

пн, 25 сент. 2023 г., 14:27 Alex Gusev ***@***.***>:

**Comment by flancer64** [comment]
Сделал, выложил на live.
