### ISSUE TITLE
Плохое масштабирование mob на компьютере 

### ISSUE THREAD

**Issue by minkinr** [flancer32/pwa-ra-mob#247]
На телефоне норм, а на экране компа как-то большевато. 
1) Главный экран выглядит чрезмерно огромным
Опция 1: уменьшить картинку текущей программы в 2-4 раза
Опция 2: масшатбировать все на 80% 
![Снимок экрана 2023-09-27 180737](https://github.com/flancer32/pwa-ra-mob/assets/103753072/0278fc2e-4eff-4d99-89e7-afe0fdc00387)

2) Конструктор тоже выглядит большеватым.  Уменьшить картинку программ в 1,5 раз или все уменьшить на 20%
![Снимок экрана 2023-09-27 181402](https://github.com/flancer32/pwa-ra-mob/assets/103753072/46098e8b-110f-4bea-8c51-3d79474fb4ed)
![Снимок экрана 2023-09-27 181458](https://github.com/flancer32/pwa-ra-mob/assets/103753072/0a59c769-eab8-46ef-b19a-e6bf76ee0949)

**Comment by flancer64** [comment]
Да, так и есть. Мы изначально делали пользовательский интерфейс только под мобильные. Начиная с макетов в Figma. Основывались на предположении, что и доктора, и пациенты в основном будут пользоваться мобильными устройствами. Десктопный интерфейс должен значительно отличаться от смартфоновского по структуре. В общем, это довольно большой пласт работы - десятки часов. Начиная с макетов десктопного layout'а.

Самое простое решение - не использовать на десктопах приложение в полное окно:

![image](https://github.com/flancer32/pwa-ra-mob/assets/5052385/9aa554e0-476d-4c3f-a473-03c338dc0628)

Если всё-таки нужна и десктопная версия, то нужно быть готовым к большим изменениям.

**Comment by flancer64** [comment]
Как вариант, можно поставить ограничения на ширину интерфейса и отцентровать его на экране. Это быстро.

**Comment by flancer64** [comment]
В принципе, да - можно малой кровью добиться какого-то положительного эффекта.

@minkinr , если есть ещё какие-то компоненты интерфейса, которые нужно ограничить по ширине - сообщите, пожалуйста.

**Comment by flancer64** [comment]
Выложился на live.
