### ISSUE TITLE
Плеер: комментарии врача и описание

### ISSUE THREAD

**Issue by minkinr** [flancer32/pwa-ra-mob#248]
@flancer64 , внизу экрана плеера добавить "комментарии вашего  врача" и "подробное описание" раскрыващимися списками.

**Comment by flancer64** [comment]
Вот так в свёрнутом виде:
![image](https://github.com/flancer32/pwa-ra-mob/assets/5052385/417cfb82-530c-45f2-8f1f-c37e2ea45ef7)

Так в развёрнутом:
![image](https://github.com/flancer32/pwa-ra-mob/assets/5052385/3cdf24a2-c2f5-44fa-9104-88bf6df8dd9c)

**Comment by flancer64** [comment]
Выложил на live.

**Comment by minkinr** [comment]
отлично!08:29, 28 сентября 2023 г., Alex Gusev ***@***.***>:
Выложил на live.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
-- Отправлено из мобильного приложения Яндекс Почты
