### ISSUE TITLE
Оценка: смена статуса программ в кабинете doc@gmail.com ?

### ISSUE THREAD

**Issue by minkinr** [flancer32/pwa-ra-mob#255]
Александр, сколько по времени займет такая доработка - 
смена статуса программ в кабинете doc@gmail.com ? Мы их там заводим и было бы логично оттуда публиковать или снимать с публикации.

**Comment by flancer64** [comment]
У нас нет статусов у программ - только у упражнений. У упражнений есть типы:

![image](https://github.com/flancer32/pwa-ra-mob/assets/5052385/2b734af8-916c-4c6e-9ab4-69998b5fb7db)

**Comment by flancer64** [comment]
Было бы правильно заводить программы через админку, но это довольно ресурсоёмко - нужно перетаскивать функционал из мобильной части. Если вы имеете в виду задавать определённый статус программе от имени doc@gmail.com, то часа на 2 работы.

**Comment by flancer64** [comment]
> или снимать с публикации.

А вот этот функционал у нас вообще отсутствует для программ. Если его прикручивать, то часа 4 навскидку. Придётся смотреть весь существующий функционал, относящийся к программам и добавлять соотв. флаг (enabled/disabled).

Часов за 6-8 можно добавить флаг доступности к программам и перенести конструктор программ в админку. Там совокупность кода, относящегося к этим функциям примерно одна и та же.

**Comment by minkinr** [comment]
Да, я про смену статусов в мобильной части при входе как ***@***.*** Ещё хорошо бы Примечание добавить, которое  видно только у  ***@***.*** и в desk/программы. 12:10, 16 октября 2023 г., Alex Gusev ***@***.***>:
Было бы правильно заводить программы через админку, но это довольно ресурсоёмко - нужно перетаскивать функционал из мобильной части. Если вы имеете в виду задавать определённый статус программе от имени ***@***.***, то часа на 2 работы.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
-- Отправлено из мобильного приложения Яндекс Почты

**Comment by flancer64** [comment]
Смена статуса программы от имени Тестового Доктора - часа 2. С добавлением примечания - на час больше. У нас нет этого поля в структуре данных в базе, нужно будет добавлять и миграцию базы делать.

**Comment by minkinr** [comment]
Начнем с добавления двух текстовых полей: 
1) Источник 
2) Примечание

Мы правильно друг друга понимаем, что эти поля НЕ будут видеть пользователи (видно только у  doc@gmail.com  и в desk)?

**Comment by flancer64** [comment]
> Мы правильно друг друга понимаем, что эти поля НЕ будут видеть пользователи (видно только у [doc@gmail.com](mailto:doc@gmail.com) и в desk)?

Да. В мобильном приложении они будут видны только для Тестового Доктора (doc@gmail.com)
