### ISSUE TITLE
Добавить атрибуты для программ у пользователя doc@gmail.com

### ISSUE THREAD

**Issue by minkinr** [flancer32/pwa-ra-mob#256]
В продолжении issue #255

Добавить в кабинете doc@gmail.com три текстовых поля для программ, которые видны только этому пользователю. 

1) Источник
2) Статус - текстовое
3) Примечание

Эти поля должны также отражаться в Desk/Програмы.

**Comment by flancer64** [comment]
Выложил изменения на live.

**Comment by flancer64** [comment]
При создании новой программы в конструкторе (не в редакторе) не сохраняются новые атрибуты.

**Comment by flancer64** [comment]
Выложил на live. @minkinr , я закрываю задачу, откройте, пожалуйста, если проблема повторится.
