### ISSUE TITLE
Оценка: Класс МКБ  и уровень сложности в карточку программы 

### ISSUE THREAD

**Issue by minkinr** [flancer32/pwa-ra-mob#257]
I. Оцениваем добавление в карточку программы  в doc@gmail.com надо добавить поле  "Класс МКБ". Это поле должны видеть другие врачи. Они должны иметь возможность искать по этому коду, например через фильтр

Как альтернатива пока можно вынести пока вынести название кода  в заголовок программы., но можно случайно забыть так как поля нет. 

II. Возможно связанная тема. В заголовке программы надо указывать уровень. Сейчас мы это делаем, но ставим в конце названия и его становиться не видно. Мы стали дублировать еще в начале, типа Стопа1: восстановление стопы. Уровень 1.

**Comment by flancer64** [comment]
Навскидку: 2-4 часа на оба атрибута.

**Comment by minkinr** [comment]
Сейчас поняла, что на одну программу классов МКБ может быть несколько. Пока не делаем, может еще ньюансы всплывут.

**Comment by flancer64** [comment]
Как вариант, можем добавить к программе сразу два атрибута:
* class_10
* class_11

и оба атрибута добавить на форму, чтобы можно было добавлять данные в базу. А фильтрацию и всякое можно будет прикрутить позже.

**Comment by flancer64** [comment]
Полагаю, что обсуждение функционала закончено. Закрываю задачу.
