### ISSUE TITLE
Sort programs in reverse order

### ISSUE THREAD

**Issue by minkinr** [flancer32/pwa-ra-mob#258]
1) Нужна сортировка программ в обратном порядке (Most recent on top).
2) Уменьшаем  размер картинки в 2-3 раза. 

![image](https://github.com/flancer32/pwa-ra-mob/assets/103753072/8e7e7d6f-7547-4905-9426-0e5e6363aea9)

**Comment by flancer64** [comment]
Получается как-то так (добавил ещё идентификатор программы):
![image](https://github.com/flancer32/pwa-ra-mob/assets/5052385/fff54879-20dc-4e8d-8d4c-08d61ca3727f)

**Comment by flancer64** [comment]
Выложился на live.
