### ISSUE TITLE
Bug: Не грузится mob  на компе, chrome.

### ISSUE THREAD

**Issue by minkinr** [flancer32/pwa-ra-mob#260]
Не грузится mob . Пишет не защищено.![20231031_191213.jpg](https://github.com/flancer32/pwa-ra-mob/assets/103753072/2153a6d7-afd6-4a8f-9ae7-eb9ea813f1f3)

**Comment by flancer64** [comment]
Сертификат в порядке. У меня нет предупреждений:
![image](https://github.com/flancer32/pwa-ra-mob/assets/5052385/130559e2-1f9b-4e8e-932d-9956f365e3dd)

**Comment by flancer64** [comment]
А посмотрите, на что браузер ругается - дабл-клик по красному "Не защищено".

**Comment by minkinr** [comment]
сейчас загрузился, но все равно пишет не защищено

**Comment by minkinr** [comment]
![20231031_194053.jpg](https://github.com/flancer32/pwa-ra-mob/assets/103753072/2df4d968-2eb2-478e-918f-6ec130531600)

**Comment by flancer64** [comment]
Вот сюда нажмите, пожалуйста. Там информация по сертификату.

![image](https://github.com/flancer32/pwa-ra-mob/assets/5052385/0e19c17a-748e-48ba-8679-2fedc32fa548)
