### ISSUE TITLE
Advanced patient

### ISSUE THREAD

**Issue by minkinr** [flancer32/pwa-ra-mob#261]
Делаем продвинутого пациента с доступом к конструктору и полным доступом до программ и упражений. Он активируется по промокоду Advanced. 

Нужно сделать для него тариф. Сейчас 100 руб. 

Добавляем дисклеймер. "Нажимая кнопку "подтвердить" я подтверждаю, что проинформирован, что данные программы составлены как общие рекомендации и  могут требовать коррекции врачом под мой конкретный случай".

**Comment by flancer64** [comment]
Вот такие роли у пользователей по итогу:
```
    DOC_BASE: 'DOC_BASE', // Full access to mobile app as a Doctor
    MGR_BASE: 'MGR_BASE', // Full access to the Desk
    MGR_CONTENT: 'MGR_CONTENT', // Content Manager (limited access to the Desk)
    PAT_ADV: 'PAT_ADV', // Full access to mobile app in the Patient mode (with discount)
    PAT_BASE: 'PAT_BASE', // Limited access to mobile app as a Patient (full price)
    PAT_PROMO: 'PAT_PROMO', // Limited access to mobile app in the Patient mode (with discount)
```

Я переименовал роли, чтобы они при сортировке группировались по типу: DOC_, MGR_, PAT_.

**Comment by flancer64** [comment]
Добавил новый тип промо-кода:
![image](https://github.com/flancer32/pwa-ra-mob/assets/5052385/3499e2d5-2666-4884-892f-732f9dde9e29)

На форме регистрации пользователей добавил дисклеймер:
![image](https://github.com/flancer32/pwa-ra-mob/assets/5052385/82188085-4777-46c8-aa5d-b6d6b95835ea)

Тариф для продвинутых пользователей установил на уровне 100/50:
```
    "priceAdv": {
      "base": 100.00,
      "renewal": 50.00
    },
```

Изменения выложил на live, структуру таблиц переделал. Новых промо-кодов для продвинутых клиентов не создавал.

**Comment by flancer64** [comment]
На моей локалке продвинутый пользователь конструктор видит:
![image](https://github.com/flancer32/pwa-ra-mob/assets/5052385/a67a3527-9823-4312-857f-f6a64b98f063)

На live не проверял.

**Comment by flancer64** [comment]
Теоретически я могу изменить роль для какого-нибудь существующего пользователя на PAT_ADV - должно будет работать.
